name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - next
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - "**/*.tftpl"
      - "**/*.go"
      - "**/README.md"
      - ".github/workflows/test.yaml"
      - ".github/workflows/release.yaml"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: "tests/go.mod"
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: "${{ secrets.GH_OIDC_ROLE_ARN }}"
          aws-region: "${{ secrets.AWS_REGION }}"
      - name: Run Tests
        shell: bash
        run: cd tests && go test -v -timeout 30m
